package edu.black.model;

import java.util.Date;

public class EasybuyNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_news.en_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer enId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_news.en_title
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String enTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_news.en_content
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String enContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_news.en_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Date enCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_news.en_id
     *
     * @return the value of easybuy_news.en_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEnId() {
        return enId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_news.en_id
     *
     * @param enId the value for easybuy_news.en_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEnId(Integer enId) {
        this.enId = enId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_news.en_title
     *
     * @return the value of easybuy_news.en_title
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEnTitle() {
        return enTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_news.en_title
     *
     * @param enTitle the value for easybuy_news.en_title
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEnTitle(String enTitle) {
        this.enTitle = enTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_news.en_content
     *
     * @return the value of easybuy_news.en_content
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEnContent() {
        return enContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_news.en_content
     *
     * @param enContent the value for easybuy_news.en_content
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEnContent(String enContent) {
        this.enContent = enContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_news.en_create_time
     *
     * @return the value of easybuy_news.en_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Date getEnCreateTime() {
        return enCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_news.en_create_time
     *
     * @param enCreateTime the value for easybuy_news.en_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEnCreateTime(Date enCreateTime) {
        this.enCreateTime = enCreateTime;
    }
}