package edu.black.model;

import java.util.Date;

public class EasybuyComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_comment.ec_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer ecId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_comment.ec_content
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String ecContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_comment.ec_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Date ecCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_comment.ec_reply
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String ecReply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_comment.ec_reply_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Date ecReplyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_comment.ec_nice_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String ecNiceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_comment.ec_id
     *
     * @return the value of easybuy_comment.ec_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEcId() {
        return ecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_comment.ec_id
     *
     * @param ecId the value for easybuy_comment.ec_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEcId(Integer ecId) {
        this.ecId = ecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_comment.ec_content
     *
     * @return the value of easybuy_comment.ec_content
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEcContent() {
        return ecContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_comment.ec_content
     *
     * @param ecContent the value for easybuy_comment.ec_content
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEcContent(String ecContent) {
        this.ecContent = ecContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_comment.ec_create_time
     *
     * @return the value of easybuy_comment.ec_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Date getEcCreateTime() {
        return ecCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_comment.ec_create_time
     *
     * @param ecCreateTime the value for easybuy_comment.ec_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEcCreateTime(Date ecCreateTime) {
        this.ecCreateTime = ecCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_comment.ec_reply
     *
     * @return the value of easybuy_comment.ec_reply
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEcReply() {
        return ecReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_comment.ec_reply
     *
     * @param ecReply the value for easybuy_comment.ec_reply
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEcReply(String ecReply) {
        this.ecReply = ecReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_comment.ec_reply_time
     *
     * @return the value of easybuy_comment.ec_reply_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Date getEcReplyTime() {
        return ecReplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_comment.ec_reply_time
     *
     * @param ecReplyTime the value for easybuy_comment.ec_reply_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEcReplyTime(Date ecReplyTime) {
        this.ecReplyTime = ecReplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_comment.ec_nice_name
     *
     * @return the value of easybuy_comment.ec_nice_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEcNiceName() {
        return ecNiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_comment.ec_nice_name
     *
     * @param ecNiceName the value for easybuy_comment.ec_nice_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEcNiceName(String ecNiceName) {
        this.ecNiceName = ecNiceName;
    }
}