package edu.black.model;

public class EasybuyProductCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product_category.epc_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer epcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product_category.epc_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String epcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product_category.epc_parent_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer epcParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product_category.epc_action
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String epcAction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product_category.epc_id
     *
     * @return the value of easybuy_product_category.epc_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEpcId() {
        return epcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product_category.epc_id
     *
     * @param epcId the value for easybuy_product_category.epc_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpcId(Integer epcId) {
        this.epcId = epcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product_category.epc_name
     *
     * @return the value of easybuy_product_category.epc_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEpcName() {
        return epcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product_category.epc_name
     *
     * @param epcName the value for easybuy_product_category.epc_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpcName(String epcName) {
        this.epcName = epcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product_category.epc_parent_id
     *
     * @return the value of easybuy_product_category.epc_parent_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEpcParentId() {
        return epcParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product_category.epc_parent_id
     *
     * @param epcParentId the value for easybuy_product_category.epc_parent_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpcParentId(Integer epcParentId) {
        this.epcParentId = epcParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product_category.epc_action
     *
     * @return the value of easybuy_product_category.epc_action
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEpcAction() {
        return epcAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product_category.epc_action
     *
     * @param epcAction the value for easybuy_product_category.epc_action
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpcAction(String epcAction) {
        this.epcAction = epcAction;
    }
}