package edu.black.model;

public class EasybuyProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer epId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String epName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_description
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String epDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_price
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Float epPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_stock
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer epStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.epc_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer epcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_bar_code
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String epBarCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_file_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String epFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_brand_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String epBrandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_product.ep_sell_count
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer epSellCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_id
     *
     * @return the value of easybuy_product.ep_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_id
     *
     * @param epId the value for easybuy_product.ep_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpId(Integer epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_name
     *
     * @return the value of easybuy_product.ep_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEpName() {
        return epName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_name
     *
     * @param epName the value for easybuy_product.ep_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpName(String epName) {
        this.epName = epName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_description
     *
     * @return the value of easybuy_product.ep_description
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEpDescription() {
        return epDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_description
     *
     * @param epDescription the value for easybuy_product.ep_description
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpDescription(String epDescription) {
        this.epDescription = epDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_price
     *
     * @return the value of easybuy_product.ep_price
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Float getEpPrice() {
        return epPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_price
     *
     * @param epPrice the value for easybuy_product.ep_price
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpPrice(Float epPrice) {
        this.epPrice = epPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_stock
     *
     * @return the value of easybuy_product.ep_stock
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEpStock() {
        return epStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_stock
     *
     * @param epStock the value for easybuy_product.ep_stock
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpStock(Integer epStock) {
        this.epStock = epStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.epc_id
     *
     * @return the value of easybuy_product.epc_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEpcId() {
        return epcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.epc_id
     *
     * @param epcId the value for easybuy_product.epc_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpcId(Integer epcId) {
        this.epcId = epcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_bar_code
     *
     * @return the value of easybuy_product.ep_bar_code
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEpBarCode() {
        return epBarCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_bar_code
     *
     * @param epBarCode the value for easybuy_product.ep_bar_code
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpBarCode(String epBarCode) {
        this.epBarCode = epBarCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_file_name
     *
     * @return the value of easybuy_product.ep_file_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEpFileName() {
        return epFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_file_name
     *
     * @param epFileName the value for easybuy_product.ep_file_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpFileName(String epFileName) {
        this.epFileName = epFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_brand_name
     *
     * @return the value of easybuy_product.ep_brand_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEpBrandName() {
        return epBrandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_brand_name
     *
     * @param epBrandName the value for easybuy_product.ep_brand_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpBrandName(String epBrandName) {
        this.epBrandName = epBrandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_product.ep_sell_count
     *
     * @return the value of easybuy_product.ep_sell_count
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEpSellCount() {
        return epSellCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_product.ep_sell_count
     *
     * @param epSellCount the value for easybuy_product.ep_sell_count
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpSellCount(Integer epSellCount) {
        this.epSellCount = epSellCount;
    }
}