package edu.black.model;

public class EasybuyOrderDetail {

    private EasybuyProduct product;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order_detail.eod_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer eodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order_detail.eo_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer eoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order_detail.ep_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer epId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order_detail.eod_quantity
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer eodQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order_detail.eod_cost
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Float eodCost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order_detail.eod_id
     *
     * @return the value of easybuy_order_detail.eod_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEodId() {
        return eodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order_detail.eod_id
     *
     * @param eodId the value for easybuy_order_detail.eod_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEodId(Integer eodId) {
        this.eodId = eodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order_detail.eo_id
     *
     * @return the value of easybuy_order_detail.eo_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEoId() {
        return eoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order_detail.eo_id
     *
     * @param eoId the value for easybuy_order_detail.eo_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEoId(Integer eoId) {
        this.eoId = eoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order_detail.ep_id
     *
     * @return the value of easybuy_order_detail.ep_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order_detail.ep_id
     *
     * @param epId the value for easybuy_order_detail.ep_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEpId(Integer epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order_detail.eod_quantity
     *
     * @return the value of easybuy_order_detail.eod_quantity
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEodQuantity() {
        return eodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order_detail.eod_quantity
     *
     * @param eodQuantity the value for easybuy_order_detail.eod_quantity
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEodQuantity(Integer eodQuantity) {
        this.eodQuantity = eodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order_detail.eod_cost
     *
     * @return the value of easybuy_order_detail.eod_cost
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Float getEodCost() {
        return eodCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order_detail.eod_cost
     *
     * @param eodCost the value for easybuy_order_detail.eod_cost
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEodCost(Float eodCost) {
        this.eodCost = eodCost;
    }

    public EasybuyProduct getProduct() {
        return product;
    }

    public void setProduct(EasybuyProduct product) {
        this.product = product;
    }
}