package edu.black.model;

import java.util.Date;

public class EasybuyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_user_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String euUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_user_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String euUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_password
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String euPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_sex
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String euSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_birthday
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Date euBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_identity_code
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String euIdentityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_email
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String euEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_mobile
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String euMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_address
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String euAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_login
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Double euLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_user.eu_status
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer euStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_user_id
     *
     * @return the value of easybuy_user.eu_user_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEuUserId() {
        return euUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_user_id
     *
     * @param euUserId the value for easybuy_user.eu_user_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuUserId(String euUserId) {
        this.euUserId = euUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_user_name
     *
     * @return the value of easybuy_user.eu_user_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEuUserName() {
        return euUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_user_name
     *
     * @param euUserName the value for easybuy_user.eu_user_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuUserName(String euUserName) {
        this.euUserName = euUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_password
     *
     * @return the value of easybuy_user.eu_password
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEuPassword() {
        return euPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_password
     *
     * @param euPassword the value for easybuy_user.eu_password
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuPassword(String euPassword) {
        this.euPassword = euPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_sex
     *
     * @return the value of easybuy_user.eu_sex
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEuSex() {
        return euSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_sex
     *
     * @param euSex the value for easybuy_user.eu_sex
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuSex(String euSex) {
        this.euSex = euSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_birthday
     *
     * @return the value of easybuy_user.eu_birthday
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Date getEuBirthday() {
        return euBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_birthday
     *
     * @param euBirthday the value for easybuy_user.eu_birthday
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuBirthday(Date euBirthday) {
        this.euBirthday = euBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_identity_code
     *
     * @return the value of easybuy_user.eu_identity_code
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEuIdentityCode() {
        return euIdentityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_identity_code
     *
     * @param euIdentityCode the value for easybuy_user.eu_identity_code
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuIdentityCode(String euIdentityCode) {
        this.euIdentityCode = euIdentityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_email
     *
     * @return the value of easybuy_user.eu_email
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEuEmail() {
        return euEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_email
     *
     * @param euEmail the value for easybuy_user.eu_email
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuEmail(String euEmail) {
        this.euEmail = euEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_mobile
     *
     * @return the value of easybuy_user.eu_mobile
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEuMobile() {
        return euMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_mobile
     *
     * @param euMobile the value for easybuy_user.eu_mobile
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuMobile(String euMobile) {
        this.euMobile = euMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_address
     *
     * @return the value of easybuy_user.eu_address
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEuAddress() {
        return euAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_address
     *
     * @param euAddress the value for easybuy_user.eu_address
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuAddress(String euAddress) {
        this.euAddress = euAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_login
     *
     * @return the value of easybuy_user.eu_login
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Double getEuLogin() {
        return euLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_login
     *
     * @param euLogin the value for easybuy_user.eu_login
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuLogin(Double euLogin) {
        this.euLogin = euLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_user.eu_status
     *
     * @return the value of easybuy_user.eu_status
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEuStatus() {
        return euStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_user.eu_status
     *
     * @param euStatus the value for easybuy_user.eu_status
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEuStatus(Integer euStatus) {
        this.euStatus = euStatus;
    }
}