package edu.black.model;

import java.util.ArrayList;
import java.util.List;

public class EasybuyProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public EasybuyProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEpIdIsNull() {
            addCriterion("ep_id is null");
            return (Criteria) this;
        }

        public Criteria andEpIdIsNotNull() {
            addCriterion("ep_id is not null");
            return (Criteria) this;
        }

        public Criteria andEpIdEqualTo(Integer value) {
            addCriterion("ep_id =", value, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdNotEqualTo(Integer value) {
            addCriterion("ep_id <>", value, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdGreaterThan(Integer value) {
            addCriterion("ep_id >", value, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ep_id >=", value, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdLessThan(Integer value) {
            addCriterion("ep_id <", value, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdLessThanOrEqualTo(Integer value) {
            addCriterion("ep_id <=", value, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdIn(List<Integer> values) {
            addCriterion("ep_id in", values, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdNotIn(List<Integer> values) {
            addCriterion("ep_id not in", values, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdBetween(Integer value1, Integer value2) {
            addCriterion("ep_id between", value1, value2, "epId");
            return (Criteria) this;
        }

        public Criteria andEpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ep_id not between", value1, value2, "epId");
            return (Criteria) this;
        }

        public Criteria andEpNameIsNull() {
            addCriterion("ep_name is null");
            return (Criteria) this;
        }

        public Criteria andEpNameIsNotNull() {
            addCriterion("ep_name is not null");
            return (Criteria) this;
        }

        public Criteria andEpNameEqualTo(String value) {
            addCriterion("ep_name =", value, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameNotEqualTo(String value) {
            addCriterion("ep_name <>", value, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameGreaterThan(String value) {
            addCriterion("ep_name >", value, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameGreaterThanOrEqualTo(String value) {
            addCriterion("ep_name >=", value, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameLessThan(String value) {
            addCriterion("ep_name <", value, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameLessThanOrEqualTo(String value) {
            addCriterion("ep_name <=", value, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameLike(String value) {
            addCriterion("ep_name like", value, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameNotLike(String value) {
            addCriterion("ep_name not like", value, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameIn(List<String> values) {
            addCriterion("ep_name in", values, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameNotIn(List<String> values) {
            addCriterion("ep_name not in", values, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameBetween(String value1, String value2) {
            addCriterion("ep_name between", value1, value2, "epName");
            return (Criteria) this;
        }

        public Criteria andEpNameNotBetween(String value1, String value2) {
            addCriterion("ep_name not between", value1, value2, "epName");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionIsNull() {
            addCriterion("ep_description is null");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionIsNotNull() {
            addCriterion("ep_description is not null");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionEqualTo(String value) {
            addCriterion("ep_description =", value, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionNotEqualTo(String value) {
            addCriterion("ep_description <>", value, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionGreaterThan(String value) {
            addCriterion("ep_description >", value, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("ep_description >=", value, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionLessThan(String value) {
            addCriterion("ep_description <", value, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionLessThanOrEqualTo(String value) {
            addCriterion("ep_description <=", value, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionLike(String value) {
            addCriterion("ep_description like", value, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionNotLike(String value) {
            addCriterion("ep_description not like", value, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionIn(List<String> values) {
            addCriterion("ep_description in", values, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionNotIn(List<String> values) {
            addCriterion("ep_description not in", values, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionBetween(String value1, String value2) {
            addCriterion("ep_description between", value1, value2, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpDescriptionNotBetween(String value1, String value2) {
            addCriterion("ep_description not between", value1, value2, "epDescription");
            return (Criteria) this;
        }

        public Criteria andEpPriceIsNull() {
            addCriterion("ep_price is null");
            return (Criteria) this;
        }

        public Criteria andEpPriceIsNotNull() {
            addCriterion("ep_price is not null");
            return (Criteria) this;
        }

        public Criteria andEpPriceEqualTo(Float value) {
            addCriterion("ep_price =", value, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceNotEqualTo(Float value) {
            addCriterion("ep_price <>", value, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceGreaterThan(Float value) {
            addCriterion("ep_price >", value, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("ep_price >=", value, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceLessThan(Float value) {
            addCriterion("ep_price <", value, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceLessThanOrEqualTo(Float value) {
            addCriterion("ep_price <=", value, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceIn(List<Float> values) {
            addCriterion("ep_price in", values, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceNotIn(List<Float> values) {
            addCriterion("ep_price not in", values, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceBetween(Float value1, Float value2) {
            addCriterion("ep_price between", value1, value2, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpPriceNotBetween(Float value1, Float value2) {
            addCriterion("ep_price not between", value1, value2, "epPrice");
            return (Criteria) this;
        }

        public Criteria andEpStockIsNull() {
            addCriterion("ep_stock is null");
            return (Criteria) this;
        }

        public Criteria andEpStockIsNotNull() {
            addCriterion("ep_stock is not null");
            return (Criteria) this;
        }

        public Criteria andEpStockEqualTo(Integer value) {
            addCriterion("ep_stock =", value, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockNotEqualTo(Integer value) {
            addCriterion("ep_stock <>", value, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockGreaterThan(Integer value) {
            addCriterion("ep_stock >", value, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("ep_stock >=", value, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockLessThan(Integer value) {
            addCriterion("ep_stock <", value, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockLessThanOrEqualTo(Integer value) {
            addCriterion("ep_stock <=", value, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockIn(List<Integer> values) {
            addCriterion("ep_stock in", values, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockNotIn(List<Integer> values) {
            addCriterion("ep_stock not in", values, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockBetween(Integer value1, Integer value2) {
            addCriterion("ep_stock between", value1, value2, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpStockNotBetween(Integer value1, Integer value2) {
            addCriterion("ep_stock not between", value1, value2, "epStock");
            return (Criteria) this;
        }

        public Criteria andEpcIdIsNull() {
            addCriterion("epc_id is null");
            return (Criteria) this;
        }

        public Criteria andEpcIdIsNotNull() {
            addCriterion("epc_id is not null");
            return (Criteria) this;
        }

        public Criteria andEpcIdEqualTo(Integer value) {
            addCriterion("epc_id =", value, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdNotEqualTo(Integer value) {
            addCriterion("epc_id <>", value, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdGreaterThan(Integer value) {
            addCriterion("epc_id >", value, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("epc_id >=", value, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdLessThan(Integer value) {
            addCriterion("epc_id <", value, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdLessThanOrEqualTo(Integer value) {
            addCriterion("epc_id <=", value, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdIn(List<Integer> values) {
            addCriterion("epc_id in", values, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdNotIn(List<Integer> values) {
            addCriterion("epc_id not in", values, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdBetween(Integer value1, Integer value2) {
            addCriterion("epc_id between", value1, value2, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("epc_id not between", value1, value2, "epcId");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeIsNull() {
            addCriterion("ep_bar_code is null");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeIsNotNull() {
            addCriterion("ep_bar_code is not null");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeEqualTo(String value) {
            addCriterion("ep_bar_code =", value, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeNotEqualTo(String value) {
            addCriterion("ep_bar_code <>", value, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeGreaterThan(String value) {
            addCriterion("ep_bar_code >", value, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ep_bar_code >=", value, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeLessThan(String value) {
            addCriterion("ep_bar_code <", value, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeLessThanOrEqualTo(String value) {
            addCriterion("ep_bar_code <=", value, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeLike(String value) {
            addCriterion("ep_bar_code like", value, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeNotLike(String value) {
            addCriterion("ep_bar_code not like", value, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeIn(List<String> values) {
            addCriterion("ep_bar_code in", values, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeNotIn(List<String> values) {
            addCriterion("ep_bar_code not in", values, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeBetween(String value1, String value2) {
            addCriterion("ep_bar_code between", value1, value2, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpBarCodeNotBetween(String value1, String value2) {
            addCriterion("ep_bar_code not between", value1, value2, "epBarCode");
            return (Criteria) this;
        }

        public Criteria andEpFileNameIsNull() {
            addCriterion("ep_file_name is null");
            return (Criteria) this;
        }

        public Criteria andEpFileNameIsNotNull() {
            addCriterion("ep_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andEpFileNameEqualTo(String value) {
            addCriterion("ep_file_name =", value, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameNotEqualTo(String value) {
            addCriterion("ep_file_name <>", value, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameGreaterThan(String value) {
            addCriterion("ep_file_name >", value, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("ep_file_name >=", value, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameLessThan(String value) {
            addCriterion("ep_file_name <", value, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameLessThanOrEqualTo(String value) {
            addCriterion("ep_file_name <=", value, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameLike(String value) {
            addCriterion("ep_file_name like", value, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameNotLike(String value) {
            addCriterion("ep_file_name not like", value, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameIn(List<String> values) {
            addCriterion("ep_file_name in", values, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameNotIn(List<String> values) {
            addCriterion("ep_file_name not in", values, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameBetween(String value1, String value2) {
            addCriterion("ep_file_name between", value1, value2, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpFileNameNotBetween(String value1, String value2) {
            addCriterion("ep_file_name not between", value1, value2, "epFileName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameIsNull() {
            addCriterion("ep_brand_name is null");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameIsNotNull() {
            addCriterion("ep_brand_name is not null");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameEqualTo(String value) {
            addCriterion("ep_brand_name =", value, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameNotEqualTo(String value) {
            addCriterion("ep_brand_name <>", value, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameGreaterThan(String value) {
            addCriterion("ep_brand_name >", value, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("ep_brand_name >=", value, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameLessThan(String value) {
            addCriterion("ep_brand_name <", value, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameLessThanOrEqualTo(String value) {
            addCriterion("ep_brand_name <=", value, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameLike(String value) {
            addCriterion("ep_brand_name like", value, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameNotLike(String value) {
            addCriterion("ep_brand_name not like", value, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameIn(List<String> values) {
            addCriterion("ep_brand_name in", values, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameNotIn(List<String> values) {
            addCriterion("ep_brand_name not in", values, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameBetween(String value1, String value2) {
            addCriterion("ep_brand_name between", value1, value2, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpBrandNameNotBetween(String value1, String value2) {
            addCriterion("ep_brand_name not between", value1, value2, "epBrandName");
            return (Criteria) this;
        }

        public Criteria andEpSellCountIsNull() {
            addCriterion("ep_sell_count is null");
            return (Criteria) this;
        }

        public Criteria andEpSellCountIsNotNull() {
            addCriterion("ep_sell_count is not null");
            return (Criteria) this;
        }

        public Criteria andEpSellCountEqualTo(Integer value) {
            addCriterion("ep_sell_count =", value, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountNotEqualTo(Integer value) {
            addCriterion("ep_sell_count <>", value, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountGreaterThan(Integer value) {
            addCriterion("ep_sell_count >", value, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("ep_sell_count >=", value, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountLessThan(Integer value) {
            addCriterion("ep_sell_count <", value, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountLessThanOrEqualTo(Integer value) {
            addCriterion("ep_sell_count <=", value, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountIn(List<Integer> values) {
            addCriterion("ep_sell_count in", values, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountNotIn(List<Integer> values) {
            addCriterion("ep_sell_count not in", values, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountBetween(Integer value1, Integer value2) {
            addCriterion("ep_sell_count between", value1, value2, "epSellCount");
            return (Criteria) this;
        }

        public Criteria andEpSellCountNotBetween(Integer value1, Integer value2) {
            addCriterion("ep_sell_count not between", value1, value2, "epSellCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table easybuy_product
     *
     * @mbg.generated do_not_delete_during_merge Tue May 01 14:15:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}