package edu.black.model;

import java.util.Date;

public class EasybuyOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order.eo_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer eoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order.eo_user_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String eoUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order.eo_user_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String eoUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order.eo_user_address
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private String eoUserAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order.eo_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Date eoCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order.eo_cost
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Float eoCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easybuy_order.eo_status
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    private Integer eoStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order.eo_id
     *
     * @return the value of easybuy_order.eo_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEoId() {
        return eoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order.eo_id
     *
     * @param eoId the value for easybuy_order.eo_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEoId(Integer eoId) {
        this.eoId = eoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order.eo_user_id
     *
     * @return the value of easybuy_order.eo_user_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEoUserId() {
        return eoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order.eo_user_id
     *
     * @param eoUserId the value for easybuy_order.eo_user_id
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEoUserId(String eoUserId) {
        this.eoUserId = eoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order.eo_user_name
     *
     * @return the value of easybuy_order.eo_user_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEoUserName() {
        return eoUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order.eo_user_name
     *
     * @param eoUserName the value for easybuy_order.eo_user_name
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEoUserName(String eoUserName) {
        this.eoUserName = eoUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order.eo_user_address
     *
     * @return the value of easybuy_order.eo_user_address
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public String getEoUserAddress() {
        return eoUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order.eo_user_address
     *
     * @param eoUserAddress the value for easybuy_order.eo_user_address
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEoUserAddress(String eoUserAddress) {
        this.eoUserAddress = eoUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order.eo_create_time
     *
     * @return the value of easybuy_order.eo_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Date getEoCreateTime() {
        return eoCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order.eo_create_time
     *
     * @param eoCreateTime the value for easybuy_order.eo_create_time
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEoCreateTime(Date eoCreateTime) {
        this.eoCreateTime = eoCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order.eo_cost
     *
     * @return the value of easybuy_order.eo_cost
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Float getEoCost() {
        return eoCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order.eo_cost
     *
     * @param eoCost the value for easybuy_order.eo_cost
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEoCost(Float eoCost) {
        this.eoCost = eoCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easybuy_order.eo_status
     *
     * @return the value of easybuy_order.eo_status
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public Integer getEoStatus() {
        return eoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easybuy_order.eo_status
     *
     * @param eoStatus the value for easybuy_order.eo_status
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    public void setEoStatus(Integer eoStatus) {
        this.eoStatus = eoStatus;
    }
}