package edu.black.mapper;

import edu.black.model.EasybuyComment;
import edu.black.model.EasybuyCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EasybuyCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    long countByExample(EasybuyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByExample(EasybuyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByPrimaryKey(Integer ecId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insert(EasybuyComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insertSelective(EasybuyComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    List<EasybuyComment> selectByExample(EasybuyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    EasybuyComment selectByPrimaryKey(Integer ecId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") EasybuyComment record, @Param("example") EasybuyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExample(@Param("record") EasybuyComment record, @Param("example") EasybuyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKeySelective(EasybuyComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_comment
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKey(EasybuyComment record);
}