package edu.black.mapper;

import edu.black.model.EasybuyProductCategory;
import edu.black.model.EasybuyProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EasybuyProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    long countByExample(EasybuyProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByExample(EasybuyProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByPrimaryKey(Integer epcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insert(EasybuyProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insertSelective(EasybuyProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    List<EasybuyProductCategory> selectByExample(EasybuyProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    EasybuyProductCategory selectByPrimaryKey(Integer epcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") EasybuyProductCategory record, @Param("example") EasybuyProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExample(@Param("record") EasybuyProductCategory record, @Param("example") EasybuyProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKeySelective(EasybuyProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product_category
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKey(EasybuyProductCategory record);
}