package edu.black.mapper;

import edu.black.model.EasybuyUser;
import edu.black.model.EasybuyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EasybuyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    long countByExample(EasybuyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByExample(EasybuyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByPrimaryKey(String euUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insert(EasybuyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insertSelective(EasybuyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    List<EasybuyUser> selectByExample(EasybuyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    EasybuyUser selectByPrimaryKey(String euUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") EasybuyUser record, @Param("example") EasybuyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExample(@Param("record") EasybuyUser record, @Param("example") EasybuyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKeySelective(EasybuyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_user
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKey(EasybuyUser record);
}