package edu.black.mapper;

import edu.black.model.EasybuyOrderDetail;
import edu.black.model.EasybuyOrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EasybuyOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    long countByExample(EasybuyOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByExample(EasybuyOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByPrimaryKey(Integer eodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insert(EasybuyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insertSelective(EasybuyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    List<EasybuyOrderDetail> selectByExample(EasybuyOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    EasybuyOrderDetail selectByPrimaryKey(Integer eodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") EasybuyOrderDetail record, @Param("example") EasybuyOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExample(@Param("record") EasybuyOrderDetail record, @Param("example") EasybuyOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKeySelective(EasybuyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order_detail
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKey(EasybuyOrderDetail record);
}