package edu.black.mapper;

import edu.black.model.EasybuyNews;
import edu.black.model.EasybuyNewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EasybuyNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    long countByExample(EasybuyNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByExample(EasybuyNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByPrimaryKey(Integer enId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insert(EasybuyNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insertSelective(EasybuyNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    List<EasybuyNews> selectByExample(EasybuyNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    EasybuyNews selectByPrimaryKey(Integer enId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") EasybuyNews record, @Param("example") EasybuyNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExample(@Param("record") EasybuyNews record, @Param("example") EasybuyNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKeySelective(EasybuyNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_news
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKey(EasybuyNews record);
}