package edu.black.mapper;

import edu.black.model.EasybuyProduct;
import edu.black.model.EasybuyProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EasybuyProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    long countByExample(EasybuyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByExample(EasybuyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByPrimaryKey(Integer epId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insert(EasybuyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insertSelective(EasybuyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    List<EasybuyProduct> selectByExample(EasybuyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    EasybuyProduct selectByPrimaryKey(Integer epId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") EasybuyProduct record, @Param("example") EasybuyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExample(@Param("record") EasybuyProduct record, @Param("example") EasybuyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKeySelective(EasybuyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_product
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKey(EasybuyProduct record);


    List<EasybuyProduct> selectProductByClassId(Integer classId);
}