package edu.black.mapper;

import edu.black.model.EasybuyOrder;
import edu.black.model.EasybuyOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EasybuyOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    long countByExample(EasybuyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByExample(EasybuyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int deleteByPrimaryKey(Integer eoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insert(EasybuyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int insertSelective(EasybuyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    List<EasybuyOrder> selectByExample(EasybuyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    EasybuyOrder selectByPrimaryKey(Integer eoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") EasybuyOrder record, @Param("example") EasybuyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByExample(@Param("record") EasybuyOrder record, @Param("example") EasybuyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKeySelective(EasybuyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easybuy_order
     *
     * @mbg.generated Tue May 01 14:15:33 CST 2018
     */
    int updateByPrimaryKey(EasybuyOrder record);
}